### PR TITLE
Replace all tabs with two spaces (fixes #31)

### LINKED ISSUE #31: Get rid of all tabs

### PR DESCRIPTION
**Pull request by ayberkt**

### CODE REVIEW

**Comment by ayberkt** [comment]
@Jassob I have merely replaced the tabs with spaces and the CI test now fails. Any idea why that might be?

**Comment by ayberkt** [comment]
@Jassob since the examples depend on the date on which they are built (because of the month being mentioned in the acknowledgements page), the tests had been broken as we entered the month of April. I am not sure what an easy fix for this would be to be honest. Perhaps give the user to change the signature format in the acknowledgements page and modify the examples so that they do not make any references to the date.

By the way, I switched to using `comparepdf` as our diffing method was broken too.

**Comment by Jassob** [comment]
Ooh.. doesn't acknowledgements page pick the month from `titling`'s `\thedate` macro?

**Comment by ayberkt** [comment]
> Ooh.. doesn't acknowledgements page pick the month from `titling`'s `\thedate` macro?

I actually just noticed that the test cases contain fixed dates. The `\monthname` command is used in the acknowledgements page and setting the date manually does not seem to have any effect on this.

I guess an easy fix is to just renew the command `\monthname` to a fixed month, compromising the ability to test the date in the acknowledgements page.

**Pull request merged**
