### PR TITLE
Ignore subtitle if missing

### LINKED ISSUE #2: Omit all mentions to subtitle if none is provided

### PR DESCRIPTION
**Pull request by Jassob**
The template should respect if an author decides not to have a
subtitle. Previously it failed with inexplicable errors, originating
from inside the template (it attempts to end a line and place some
vertical space, but unless the subtitle exists the line is empty and
TeX becomes sad).
This commit makes the subtitle printing conditional.

This closes #2

### CODE REVIEW

**Comment by ayberkt** [comment]
Great! I'll take a look soon.

> This commit makes the subtitle printing conditional, but still
> warns the author that there is no subtitle.

I don't think it should warn the author by the way. It should be completely fine to not have a subtitle.

**Comment by Jassob** [comment]
> > This commit makes the subtitle printing conditional, but still
> > warns the author that there is no subtitle.
> 
> I don't think it should warn the author by the way. It should be completely fine to not have a subtitle.

Alright, I'll remove the warning then.

**Review by ayberkt — COMMENTED** [review]
Looks good and seems to work well for my thesis. One thing to consider is, do we really want the space between the title and the "Master' Thesis in ..." text in the title page to change when the subtitle is omitted? Which one do you think looks better? I cannot be sure myself.

**Comment by Jassob** [comment]
> One thing to consider is, do we really want the space between the title and the "Master' Thesis in ..." text in the title page to change when the subtitle is omitted?

The space between the subtitle and the "Master's Thesis ..." is the same as the space between the title and subtitle and therefore will be same if subtitle is omitted. 
The space that is occupied by the subtitle is difficult to account for, since it can span multiple lines.

**Comment by Jassob** [comment]
I'd vote for simply removing the subtitle and let the title be lowered to 0.5cm above the "Master's Thesis ..." line, it is the most simple solution implementation-wise and seems not too unexpected to me (considering that subtitles may span multiple lines).

**Review by ayberkt — APPROVED** [review]

**Pull request merged**
