### PR TITLE
Add CI with golden testing

### LINKED ISSUE #9: Set up continuous testing
@Jassob I created a Docker image equipped with the minimum requirements for compiling this template (including the fonts): https://hub.docker.com/r/ayberkt/latex.

Can you use it to set up CI testing using GitHub actions? I have no idea how to use it since I use GitLab for this purpose.

### PR DESCRIPTION
**Pull request by Jassob**
Added a portable POSIX shell script that performs the golden
testing. It creates a temporary working folder for typesetting the
documents and then compare the output to the already checked in golden
file.

# TODO
- [x] Add a README.md in test/
- [x] Make sure it works

### CODE REVIEW

**Comment by ayberkt** [comment]
By the way, I should note that there have been a few deliberate deviations from the style of the provided template such as the header formatting and the positioning of page numbers. We will have to account for that for the tests to work.

**Comment by Jassob** [comment]
> I should note that there have been a few deliberate deviations from the style of the provided template such as the header formatting and the positioning of page numbers. We will have to account for that for the tests to work.

Yes, and we do that by simply committing a new golden file, after a visual review that the new PDF only contains intended changes.

**Comment by Jassob** [comment]
@ayberkt The docker image lacks certain packages (the first that comes up is `moreverb.sty`), could you please update it to include enough packages to build the template? 

It might be that we actually need `texlive-full` or whatever it is called in Alpine.

**Comment by Jassob** [comment]
I can of course fix it on my end, if you prefer to keep `docker.io/ayberkt/latex` small :)

**Comment by ayberkt** [comment]
> @ayberkt The docker image lacks certain packages (the first that comes up is `moreverb.sty`), could you please update it to include enough packages to build the template?

I've installed `texlive-full` on `ayberkt/agda:v2`.

**Comment by Jassob** [comment]
> I've installed `texlive-full` on `ayberkt/agda:v2`.

Thanks, but that image does not contain `latexmk`...

**Comment by Jassob** [comment]
An alternative would of course be if we could have a minimal TeXLive distribution (so that XITS are included, although we can drop that too if we let the end users choose fonts themselves) and then use tectonic to download all the required LaTeX files.

**Comment by Jassob** [comment]
Okay, so after some more experimentation I've found that it is **not** enough to simply diff the PDFs, since the creation date etc. are persisted as metadata and therefore differs between the golden files and the test files.

To solve this issue I decided to convert the PDFs to PostScript files, using `pdftops`, and diff the PS instead.

**Comment by Jassob** [comment]
I also made a custom Dockerfile that depends on a slimmed down Debian image with tectonic installed. 

A curious thing is that I try to "prime" the Tectonic cache by typesetting a document which requires the same set of packages as the template, but that cache is for some reason lost and it instead needs to download _EVERYTHING_, even the "latex format" definition... As of now, I don't know why...

**Comment by ayberkt** [comment]
> Okay, so after some more experimentation I've found that it is **not** enough to simply diff the PDFs, since the creation date etc. are persisted as metadata and therefore differs between the golden files and the test files.

Great job, thanks!

**Comment by ayberkt** [comment]
@Jassob is it possible to access the generated PDF as an artifact? It would be nice to include a link to that in the README.

**Comment by Jassob** [comment]
> @Jassob is it possible to access the generated PDF as an artifact? It would be nice to include a link to that in the README.

It is very much possible, do you think we should upload only the tests that fail? 

If you want to show example PDFs, you can link to the "golden files" in `test/{sample1,parskipped-report}/main.golden.pdf`.

**Pull request merged**
