### PR TITLE
Get keywords to work (fixes #3)

### LINKED ISSUE #3: Keywords are not working
For some reason, I can't get `\keywords` command to work correctly.. 

With this example, I expect the keywords in the abstract to be "Some, random, words" but instead some strange default value ("keywords") pop ups instead.  

```tex
\input{template/template}

\title{The Thesis Title}
\author{John Doe}

\keywords{Some, random, words}

\begin{document}

\begin{abstract}
  \lipsum[1-3]
\end{abstract}

\end{document}
```

Note that this is with the following patch applied, as the keywords otherwise are hard-coded to "foo, bar"

```diff
diff --git a/settings.tex b/settings.tex
index 31f438f..0b355e7 100644
--- a/settings.tex
+++ b/settings.tex
@@ -62,7 +62,7 @@
   }
   {% KEYWORDS (MAXIMUM 10 WORDS)
    \vfill
-   Keywords: foo, bar
+   Keywords: \@keywords

    \newpage	% Create empty back of side
    \thispagestyle{empty}
```

The result is available [here](https://github.com/ayberkt/chalmers-msc-thesis-template/files/4187844/main.pdf).

### PR DESCRIPTION
**Pull request by ayberkt**

### CODE REVIEW

**Comment by Jassob** [comment]
Good find! I really feel that I should get to know (La)TeX better...

**Comment by Jassob** [comment]
Should we update the other macros as well, like `supervisor`, `division` etc? Or do you think it is waste of time since they actually work?

**Comment by ayberkt** [comment]
> Should we update the other macros as well, like `supervisor`, `division` etc? Or do you think it is waste of time since they actually work?

That might be a good idea to get rid of `makeatletter/makeatother` altogether.

**Comment by Jassob** [comment]
I'm on it!

**Comment by Jassob** [comment]
See https://github.com/ayberkt/chalmers-msc-thesis-template/pull/6

**Pull request merged**
