### PR TITLE
Add support for cover images

### LINKED ISSUE #30: Support cover image
Now that we have conditional typesetting for both subtitles and divisions, it would be rather simple to use the same mechanism to support cover image.

### PR DESCRIPTION
**Pull request by Jassob**
This commit adds support for specifying a cover image and its subtitle
using the command `\coverfigure{figure-path}{figure-caption}`.

The golden files needed updating because we no longer typeset "Cover:
Description of the picture on the cover page (if applicable)", but
instead the figure-caption or nothing if omitted.

The test runner script needed updating so that it also copied over any
resources such as images etc.

This fixes #30

### CODE REVIEW

**Comment by Jassob** [comment]
I am not convinced that I've found the simplest user-facing API for setting a cover image.

- Should we force a cover image to have a caption? 
- Can it be made clearer that the command requires two arguments?
- Is \coverfigure a good name for the macro?

**Comment by ayberkt** [comment]
> Should we force a cover image to have a caption?

In my opinion, yes but it should not be a figure caption. It should just be a short explanation that goes in the imprint page along with the credits. We are not taking the credits as input either, right?
 
>  Can it be made clearer that the command requires two arguments?

I'm not sure to be honest. Does it fail if the second argument is not provided?

>  Is \coverfigure a good name for the macro?

How about `\coverimage`?

Also, I'm not even sure if this should be a figure. Will it show up in the list of figures? I think it shouldn't and it should be just an inline image, conceptually.

**Comment by Jassob** [comment]
> > Should we force a cover image to have a caption?

> In my opinion, yes but it should not be a figure caption. It should just be a short explanation that goes in the imprint page along with the credits. 

That is how it is done now, I more or less made the old template code conditional.
I think that if we want to force users to always provide a description/caption with their cover images, then we could have a single macro that takes both as argument, but if we would allow an image without description then it makes sense to have two macros.

> > Can it be made clearer that the command requires two arguments?
> 
> I'm not sure to be honest. Does it fail if the second argument is not provided?
> 

It does fail, but with the same type of inexplicable (to a user) error (no line to end), which indicates that it could be made to work by inspecting the arguments.. However that probably means that TeX/LaTeX would slurp in any token as it's second argument.. I am not sure about this. 

> > Is \coverfigure a good name for the macro?
> 
> How about `\coverimage`?

Yeah, I think it is better. However, it still suffers from the issue that it is not too clear that we expect two arguments.. Which of course could be easily solved with documentation. It is not as if anyone using this template would guess the macro names anyway...

> Also, I'm not even sure if this should be a figure. Will it show up in the list of figures? I think it shouldn't and it should be just an inline image, conceptually.

It does not show up in the figure list, as you say it is only an `\includegraphics[..]{..}`

**Comment by Jassob** [comment]
All right, so I've made sure that the `\coverimage` macro (yes, I updated the name) now inpects its arguments and outputs quite clear and helpful errors (if I may say so myself).

 Attempting to use \coverimage with an empty path (probably the least plausible error) causes LaTeX to break and print:

```
! Class chalmers-msc-report Error: \coverimage : Empty IMAGE-PATH
(chalmers-msc-report)              Usage: \coverimage {IMAGE-PATH}{IMAGE-CAPTIO
N} .

See the chalmers-msc-report class documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.18 \coverimage{}{My caption}
                               % path to cover image
? H
You called \coverimage like this: \coverimage{}{My caption} (or in some other w
ay that caused \LaTeX to think that the second argument is empty), but IMAGE-PA
TH cannot be empty.
Insert a path to \coverimage first argument, i.e.
\coverimage {path/to/my-graphic}{My caption}.
```

`? H` means that I typed in a H to get a more detailed help text.

And omitting the second argument gives almost the same error, but where IMAGE-CAPTION replaced IMAGE-PATH.

**Comment by Jassob** [comment]
I used the `ClassError` error printing macro, because I think we might eventually want to make this into a document class.

**Comment by ayberkt** [comment]
> `? H` means that I typed in a H to get a more detailed help text.

Wow, that's amazing :open_mouth:. I didn't know there was such a thing.

**Comment by Jassob** [comment]
> > `? H` means that I typed in a H to get a more detailed help text.
> 
> Wow, that's amazing open_mouth. I didn't know there was such a thing.

Neither did I, I am quite amazed myself!

I more or less stole the error message from this good resource [on writing your own packages or classes](http://ftp.acc.umu.se/mirror/CTAN/macros/latex/base/clsguide.pdf).

**Review by ayberkt — APPROVED** [review]
Looks good.

**Pull request merged**
